### ISSUE TITLE
Allow and control writes to globals/endowments

### ISSUE THREAD

**Issue by kumavis** [Agoric/SES#142]
It would be useful, when appropriate and clearly configured, to be able to allow code to write to globals/endowments/something.

I [experimented with this](https://github.com/MetaMask/sesify/compare/MetaMask:5692049...MetaMask:eb91108
), using the [per-evaluate sloppyGlobals feature](https://github.com/Agoric/realms-shim/pull/33). The experiment is likely bad and insecure, but allowed me to explore allowing modules to write and read from shared globals when configured to do so.

**Comment by kumavis** [comment]
I see, this can happen in compartments by defining setters on the compartment global

**Comment by kumavis** [comment]
Here is another experiment using setters on compartment globals. it also no longer uses the `endowments` parameter. The experiment is likely bad and insecure.
https://github.com/MetaMask/sesify/compare/MetaMask:5692049...MetaMask:global-writes2

**Comment by kumavis** [comment]
@erights, @michaelfig, @jfparadis
can you evaluate my approach to allowing global writes?
please see the compartments version linked in the comment above this

**Comment by michaelfig** [comment]
You may want to `harden` the globals after you're done assigning the properties to them.  That would prevent any global assignments except for the ones you're allowing.

**Comment by kumavis** [comment]
@michaelfig true, though it's their own global I suppose they can do what they want with it. Shouldn't impact anyone else.

**Comment by kumavis** [comment]
ok I'm sufficiently happy with this option.
