### ISSUE TITLE
Question: How to run multiple realms in one iFrame?

### ISSUE THREAD

**Issue by danfinlay** [Agoric/SES#157]
I know @kumavis already figured this out, but he's asleep right now. How can I use SES to initiate multiple realms from a single iFrame? Or should I use the Realms shim directly for that?

**Comment by erights** [comment]
`SES.makeSESRootRealm()`

See https://ses-secure-ecmascript.readthedocs.io/en/latest/getting-started.html

**Comment by danfinlay** [comment]
So each call to `s.evaluate()` has its own frozen scope and primordials?

**Comment by danfinlay** [comment]
This seems to do what I was hoping, thank you!

**Comment by erights** [comment]
Each call to `SES.makeSESRootRealm()` makes a new root realm. Each root realm has its own frozen primordials. For the rest of your question, we need to distinguish "global scope" from "scope"  In the example:

```js
s.evaluate('1+2'); // returns 3
s.evaluate('1+a', {a: 3}); // returns 4
```

both evaluations are in the same realm, and use the same frozen primordials, the same global object, the same global scope, but different scope. In particular, the scope in which the string's free variables are looked up has two levels --- the endowments first, and then the global scope. The endowments scope for the first evaluation is empty. For the second, the variable `a` is initially bound to the value 3. After the endowments scope, both evaluations have the same global scope.

**Comment by danfinlay** [comment]
This is perfect, thank you!
