### ISSUE TITLE
SES under Node.js

### ISSUE THREAD

**Issue by michaelfig** [Agoric/SES#25]
Hi,

I'm having a dickens of a time trying to use SES under Node.js.  Is there any guidance as to how to import it into a plain Node.js main script (version 8.5 or above)?  I just can't figure out the combination of `require`, `import`, `--experimental-modules`, and which file to use, given that I have in t.js something like:

```javascript
const SES = require('./ses/src/SES.js');
console.log(SES);
```

and the SES sources are checked out into `./ses`.

Help would be greatly appreciated.

Thanks,
Michael.

**Comment by michaelfig** [comment]
Oh, to be specific, I always get some kind of error like:

```
SyntaxError: Unexpected token import
```

or:

```
{}
```

(the require worked, but there was no exported names).

**Comment by michaelfig** [comment]
@warner, would you be able to add to this issue the import line needed after running:

``'
$ npm install ses
$ node -r esm
```

?

Thanks,
Michael.

**Comment by katelynsills** [comment]
Hi @michaelfig. We [recently made it easier](https://github.com/Agoric/SES/commit/63665d7f2d08166f2aca3eecf3f6b7df5eacdbdb) to use SES from Node.js. For anyone else who might be reading, now you just need to follow the steps you would normally take to install and use a package:

```
$ npm install --save ses
$ node
> const SES = require('SES');
undefined
> const r = SES.makeSESRootRealm();
undefined
> r
Realm {}
> r.evaluate(`"abc"`);
'abc'
```

**Comment by michaelfig** [comment]
@katelynsills, Looks great.  Thanks.
