### ISSUE TITLE
freeze "unreachable" primordials

### ISSUE THREAD

**Issue by warner** [Agoric/SES#3]
We're currenly only freezing primordials that are reachable by property+prototype traversal from the RootRealm's global object. This misses things that are only reachable by syntax, like `ArrayIteratorPrototype`. We need to get the full list (maybe from `anonIntrinsics.js` for now, but ideally from some Realms API that will be updated as the platform adds new one) and add it to the `primordialRoots` in `deepFreeze.js`.

Until we do this, programs that use any of these primordials will not be defensive against attacker code that seeks to mutate them.

**Comment by erights** [comment]
It also means that subgraphs that were supposed to be isolated from each other can use this shared mutable state to talk to each other --- even if they have no other use for it.

**Comment by erights** [comment]
Relevant issue thread https://github.com/tc39/ecma262/issues/1417

**Comment by erights** [comment]
In progress on the whitelist-2 branch. See https://github.com/Agoric/SES/issues/26#issuecomment-457676194
