### ISSUE TITLE
denied object are still accessible by creating a new child realm

### ISSUE THREAD

**Issue by warner** [Agoric/SES#30]
There are some supposedly-denied objects that may in fact be re-accessible by creating a new child Realm and pulling the functionality from the child. #27 used this to access `Date.now()`, which we fixed, but the current code also tries (and fails) to block access to things like:

* `Math.random()`
* `Intl.NumberFormat()`
* `Error.prototype.stack`

Our plan is to fix these by registering a shim which locks off access to these things, such that the shim is inherited by all new child Realms too.

**Comment by warner** [comment]
BTW our current fix replaces these sources of nondeterminism with errors, but some more sophisticated approaches come to mind:

* `Intl.NumberFormat()` is only a problem if you call it without arguments, in which case it uses the platform-configured default locale (which is precisely the source of non-determinism we want to block). Calls that provide a specific locale aren't a problem. So the first improvement is to only throw an error when the argument is missing. The same issue applies to `Intl.DateTimeFormat()`.
* It would also make sense to provide the default locale as an argument to the Realm-creating call. Basically every new Realm/SESRealm we create will behave identically unless you provide arguments to allow something different, and the argument you add needs to specify how the Realm can differ from this neutral flavor. That argument might say "pretend we're in `LOCALE=fr`", or it might say "reveal the platform's actual locale", but it's always up to the creator of the Realm which one to use. Setting the default locale would also address `Intl.getCanonicalLocales()` quite directly.
* `Math.random()` could conceivably be replaced by a seeded PRNG, making the values it returns a deterministic function of the seed and the number of calls. Or it could be replaced by a fixed value (e.g. 4, as specified in [XKCD-221](https://www.xkcd.com/221)). The former would enable Monte Carlo -style simulations to still work reasonably well while still remaining reasonably deterministic (the guest code would need to be vigiliant about exactly how many `Math.random()` calls it makes, and not reordering things casually).

`Error.prototype.stack` is an engine-specific debugging tool. We must block it for safety, but in the longer run we need to provide the host code to get debugger access to the guest code (and not the other way around). The act of creating a new Realm should get the caller some sort of debugger object. One approach might be to capture the return value from the shim's evaluation, and return those to the caller. Another could be to provide a mutable object in the evaluation's global environment (i.e. as endowments), and the shim could add properties to it, to pass the debugger object back that way.

Another approach we've discussed is to let the list of shims become a list of strings-or-callables. For each callable, we invoke it with access to the new realm's indirect evaluator function. The callable could inject the normal shim code as usual, but it gets access to the second argument (endowments) and the return value, give it an opportunity to do more. We could also give the callables a second argument, an object that gets attached to the Realm controller, on which we can collect things like this debugger object.

The challenge, of course, is that doing anything but evaluating a string runs a higher risk of leaking objects between realms.

We want a shim/callback added by one realm to be imposed upon all child subrealms. But when callbacks are involved, we need to avoid confusing those callbacks: if A creates B with a debugger-adding shim/callback, and then later B creates C, we don't want A to accidentally wind up with C's debugger when it thought it had B's.

**Comment by bathos-wistia** [comment]
> Calls that provide a specific locale aren't a problem.

Is this different? I though the available locales were implementation-specific. The functions only require that the language tags are syntactically valid, but if they don’t support them, they seem to fall back on system defaults.

```js
Intl.NumberFormat('xx').resolvedOptions().locale === YOUR_DEFAULT_LOCALE?
```

**Comment by warner** [comment]
Ugh. Yes, you're right, if those will fall back to a system-defined value, then we either have to trap/reject that case, or reject their use entirely. Sigh.

**Comment by erights** [comment]
Replacing `Math.random()` with a cryptographically strong pseudo-random number generator whose seed is unknown by anyone would prevent it from being a communications channel, but is of course incompat with deterministic replication. Doing it with an agreed seed, to enable deterministic replication, also makes it a reliable and overt communications channel. The fundamental sin here is that it is mutable primordial state. As with `Date.now()` these choices can be configuration parameters, but the default must be to censor `Math.random()` by having an attempt to use it throw an error.

**Comment by erights** [comment]
> or it might say "reveal the platform's actual locale

Noting that this phrase, if taken literally, might enable the recovery of a denied "actual locale" by creating a new realm, which is exactly the transitive denial issue this bug is about.

**Comment by bathos-wistia** [comment]
IIRC Node ships by default with only support for "en" (not "en-US"), motivated by a desire to keep the runtime small (bytewise). So the set of language tags supported by all engines is either { "en" } or {}.

Annex A of ECMA 402 might be helpful since it’s more or less a list of everything in Intl that might cause trouble for SES: 

https://tc39.github.io/ecma402/#annex-implementation-dependent-behaviour

**Comment by warner** [comment]
Our 0.2.0 release fixes these three leaks. If/when we decide to expose the deterministic parts of `Intl`, we'll have to think more carefully about the behavior of the default (or non-supported) locales, but for now I think blocking them entirely is sufficient.
