### ISSUE TITLE
change "harden" to share a WeakMap of already-frozen objects

### ISSUE THREAD

**Issue by warner** [Agoric/SES#4]
Our current `def()` function currently does too much work: it doesn't remember what's been frozen already, so it will re-freeze things like Function.prototype every time. To fix this, deepFreeze() needs to be turned into a "Freezer" object that retains a WeakMap of everything it has ever frozen, def() should take a Freezer, and the def() exposed as a global should close over the Freezer and deliver it here. deepFreezePrimordials() should use that same Freezer

This isn't a security issue, merely a performance one.

**Comment by kumavis** [comment]
can you use `Object.isFrozen(obj)`

**Comment by erights** [comment]
No, because `Object.isFrozen` is not transitive. If `def` stopped at a frozen object, it could miss non-frozen objects that were reachable from named properties of that frozen object:

```js
const bad = Object.freeze([{}]);
// At this point, we have a frozen array containing 
// a non-frozen object in its transitive API surface.
def(bad);
```

If the call to `def` succeeds, then the transitive API surface starting at `bad` must be frozen. But an `isFrozen` check would stop too early.

**Comment by erights** [comment]
In addition to labeling this an "enhancement" I also label it a "bug" because it is a huge performance bug. Normally, if there is no deviation from correct overt behavior I avoid "bug". But the performance shortfall here is huge.

**Comment by erights** [comment]
Noting again here that we're likely to change terminology from "deeply frozen" and such to "hardened".

**Comment by dckc** [comment]
This weakmap seems to be global mutable state. Why is that ok in this case?

Also, is it shared between realms? Between calls to require('harden')?

**Comment by warner** [comment]
> This weakmap seems to be global mutable state. Why is that ok in this case?
> 
> Also, is it shared between realms? Between calls to require('harden')?

I'm going to open a separate issue to discuss this, I think we have an answer but I don't want to lose visibility when I close this as fixed in a few minutes.
