### ISSUE TITLE
add simple `require()` to the SES environment, replace global Nat/def with requires

### ISSUE THREAD

**Issue by warner** [Agoric/SES#51]
To help with #13, we're going to add a rudimentary `require()` to the SES environment. It will initially only accept one of three names: `nat`, `def` (which will be renamed `harden`), and `ses`. Rather than having `Nat`/`def`/`SES` be injected onto the global namespace, we'll instead inject `require` into that namespace, and you'll get the other symbols by using `require()` exactly as you would outside of SES:

```
const SES = require('ses');
const Nat = require('nat');
```

The object you get back when using `require('ses')` inside a SES realm will be different than what you'd get from outside of one. For `Nat` they'll be the same but `SES` needs to build a separate version for each nested realm, and `def`/`harden` will return a hardener that already knows about all the primordials that are already frozen.

This `require()` will throw an exception if you give it any other module name: it is not yet a general-purpose module loader (although of course this is a natural place to build one in the future). We'll have to decide later about `require`/CJS vs `import`/es6 style.. for now, a basic `require()` should be enough to let us share code between SES and non-SES environments.

**Comment by warner** [comment]
Note to self: per the discussion in https://github.com/Agoric/PlaygroundVat/pull/13#issuecomment-463314990 , @jdalton is planning on making a new `esm` release (something after 3.2.5) that offers a config option to control the renaming (instrumentation) of functions like `console` and `eval`. When that is available, we should use it to tell `esm` to not rename `eval`, and then rewrite the hack in `makeRequire`
(https://github.com/Agoric/SES/blob/a33cb8952b243dfd863c1df9c32f20dfadf4715c/src/bundle/make-require.js#L8-L12)

**Comment by warner** [comment]
As mentioned in https://github.com/Agoric/SES/issues/9#issuecomment-465003139 , instead of adding a `requireMode:` to the `SES.makeSESRootRealm()` arguments, we should build a helper function (maybe spelled `s.makeRequires()` that takes a configuration object and produces an in-Realm `require` function. The configuration object can start as a table mapping the `NAME` in `require(NAME)` to a description of what that require should supply, but can eventually turn into a manifest that describes the full tree of dependencies and their constraints.

**Comment by dckc** [comment]
This is done, to my satisfaction.

I struggled a bit for lack of docs, but #67 was enough clues for me to write https://github.com/dckc/do-your-worst/blob/master/loader.js
