### ISSUE TITLE
publish on NPM

### ISSUE THREAD

**Issue by warner** [Agoric/SES#6]
We should get this up on npm, under the name `SES`.

@kriskowal, does this seem worthy of claiming the `ses` name on npm? I see that you've got an old snapshot of Caja published under that name right now (last updated about four years ago).

@jfparadis, this repo incorporates the Realms shim by using a git submodule (which is currently a week or two out of date). Would it make more sense to get Realms into NPM too? Then SES could just have a dependency on some version of Realms. Actually, it would be both a regular dependency and a `devDependency`, because we must stringify+flatten the whole Realms constructor to build the SES shim string. (We'd probably need to pin the version in both, to avoid allowing downstream users to get one form of Realm on their top-level SES environment, and a different version for new Realms built inside that one).

cc @erights

**Comment by warner** [comment]
@kriskowal great, thanks. Could you add me on NPM as a Maintainer so I can publish new versions there? My NPM username is `warner` (https://www.npmjs.com/~warner).

**Comment by warner** [comment]
Oh and I got email from @jfparadis who suggested that we stick to using a git submodule for now, to let the Realms proposal (both shim and spec) to continue evolving without being pinned down to compatibility with published versions, which makes a lot of sense to me too.

**Comment by kriskowal** [comment]
@erights is already an owner on the npm package. https://www.npmjs.com/~erights and can run `npm owner add warner ses` on his credentials to bless you with publisher rights. I’m sure you appreciate my desire to avoid role-playing the confused deputy.

**Comment by warner** [comment]
Heh :). Yep, that should be plenty.. thanks!

**Comment by warner** [comment]
Published as 0.1.2 at https://www.npmjs.com/package/ses/v/0.1.2 , thanks all!

BTW, for some reason the (previous) package has been downloaded about 150 times a week for the last several months. I don't know why.. I blame robots. It's not listed as a dependency of anything public on NPM.
