### ISSUE TITLE
expose harden

### ISSUE THREAD

**Issue by kumavis** [Agoric/SES#69]
`def` was previously available on SES

is this the current correct way to attain the `harden` function?
```js
const realm = SES.makeSESRootRealm()
const harden = realm.makeRequire({ '@agoric/harden': true })('@agoric/harden')
```

**Comment by katelynsills** [comment]
Hi @kumavis, right now `realm.makeRequire()` returns a req which should be passed in as part of the endowments. This allows the code that is evaluated to require harden and use it. (This example comes from [one of the unit tests](https://github.com/Agoric/SES/blob/859741713e3b648a773deb33fee6cbdfae23da95/test/test-require.js#L63), so the objects are bit strange.) 

```js
const realm = SES.makeSESRootRealm();
const req = realm.makeRequire({ '@agoric/harden': true });
function check() {
  const harden = require('@agoric/harden');
  const defMe1 = function me() {};
  defMe1.other = {};
  const defMe2 = harden(defMe1);
  return { defMe1, defMe2 };
}
const { defMe1, defMe2 } = s.evaluate(`${check}; check()`, { require: req });
```

Also, makeRequire() is still pretty early - in particular it's not transitive (the code being required can't use require() itself). We'll be working on improving it and turning it into a generalized safe import tool for modules.

**Comment by kumavis** [comment]
@katelynsills thanks for the quick response 

I was surprised to see the `require` added to SES. Seems like something that should be the responsibility of a higher module, and leave SES as a small helpful wrapper around FrozenRealms. I plan to join the call this Thursday and can elaborate.
